### ISSUE TITLE
Not working for JetBrains Rider (IntelliJ-based IDE)

### ISSUE THREAD

**Issue by tarikguney** [BarRaider/streamdeck-supermacro#1]
I am using JetBrains Rider for C# development, and wanted to create a profile for Rider which includes macro keys like `Build`, `Run Tests`, etc. For the key map I am using, the shortcut to run the unit tests is `CTRL` + `;` + `R` and this is the macro I have tried: `{{ctrl}{;}}{{pause500}}{{r}}`; and for some reason, instead of running the unit tests, I keep seeing `r` printed on my test file after some delay.

**Comment by BarRaider** [comment]
Hey @tarikguney 
I think what you're looking for is:
{{ctrl}{;}{r}}
