### ISSUE TITLE
I am having trouble with this macro

### ISSUE THREAD

**Issue by vjeffrandolph** [BarRaider/streamdeck-supermacro#13]
I am trying to use this macro to remove a complete line of text from notepad.

{{home}}{{shift}{end}}{{delete}}

When I execute the keystrokes by hand, it works, but  through Super Macro it acts as if it doesn't recognize that I've pressed SHIFT at the same time as END.

Thanks!!

**Comment by BarRaider** [comment]
Hi, 
I can confirm it's happening to me too, not sure why yet and I will take a look.
In the mean time, this seems to be working: {{home}}{{shift}{rshift}{end}}{{delete}}

**Comment by vjeffrandolph** [comment]
That works for me.  Thanks for the help!!
