### ISSUE TITLE
Super Macro Toggle loses icon

### ISSUE THREAD

**Issue by TomberWolf** [BarRaider/streamdeck-supermacro#14]
I've created a Super Macro Toggle with two custom icons.
After switching a to another profile on Stream Deck, the icon switches back to the default icon with the three cogs.

**Comment by BarRaider** [comment]
Thanks for reporting the bug. It has been fixed and will be released in the next version.
If you would like to get it sooner, it is already available on my Discord server. Link at https://barraider.github.io
