### ISSUE TITLE
{{PRINT}} doesn't seem to work in SuperMacro.

### ISSUE THREAD

**Issue by esemwy** [BarRaider/streamdeck-supermacro#2]
I'm using [Greenshot](https://getgreenshot.org/) for screen grabs on Windows 10. I've previously used [AutoHotStreamDeck](https://github.com/evilC/AutoHotStreamDeck) for producing the correct hot keys without any problem. Programming ```{{print}}``` into a Super Macro doesn't seem to do anything, nor do any other (```{{ctrl}}{{print}}```, ```{{alt}}{{print}}```, etc.) combinations that I would like to use. Any suggestions?

**Comment by tarikguney** [comment]
For some reason, some apps act differently when the key presses come from the actual keyboard or an app like this plugin. Similar issues happen to me for JetBrains IntelliJ based IDE named Rider. They are not registered for some reason even though I changed the timing between each press, etc. No luck.

**Comment by esemwy** [comment]
Might be worth checking how [AutoHotStreamDeck](https://github.com/evilC/AutoHotStreamDeck) does the event insertion. I’m not enough of a Windows programmer to know what’s what so far as different APIs are concerned, but I’ll take a look and see if I can add anything useful.

**Comment by BarRaider** [comment]
Sorry for the delay here. The command you're looking for is {{SNAPSHOT}} . A new version of the plugin will be released in a few days. You can test it out prior on my discord server (link at https://barraider.github.io )
