### ISSUE TITLE
Could not send json because the plugin is not registered

### ISSUE THREAD

**Issue by MarioBinder** [BarRaider/streamdeck-supermacro#20]
Macros are not working anymore. 
I found some errors in the log

EGCAPILiteDLL::LoadDLL():                       
Could not load EGCAPILite.dll

<:snip>

EGCAPILiteDLL::Initialize():                    
mInitializeFunc is not set

<:snip>

ESDCustomPlugin::SendJSON():                    
Could not send json because the plugin is not registered

**Comment by BarRaider** [comment]
This has nothing to do with the Plugin, this is related to StreamDeck.
I recommend reinstalling Stream Deck. If it still doesn't work afterwards, please join my Discord server so we can look into it further. Link at https://barraider.github.io

**Comment by MarioBinder** [comment]
The Error occurs only when I try to use the Macro.  

ESDCustomPlugin::SendJSON():
Could not send json because the plugin is not registered

A reinstall has no affects.

**Comment by MarioBinder** [comment]
I reinstalled the plugin and it's working now. 
Thanks for your patience
