### ISSUE TITLE
Clear variables after macro runs

### ISSUE THREAD

**Issue by hoffman-thomas** [BarRaider/streamdeck-supermacro#28]
Variable names shared across macros and are not cleared after the macro finishes. This could be a security problem when dealing with sensitive data inputs. It would also be nice to have a `SECURE_INPUT` command for a message prompt that makes the input text invisible to the user. For instance:

macro 1: gets a password or other sensitive data from the user to use in some script.
```
{{INPUT:password}}
```

(separate) macro 2: is still able to access sensitive information. 
```
{{OUTPUT:password}}
```

**Comment by BarRaider** [comment]
While this is by design to not force user input for consecutive macros, I will check the option to add a command to clear variables

**Comment by hoffman-thomas** [comment]
Understood. Thanks for checking this out!

**Comment by BarRaider** [comment]
New {{VARUNSET}} and {{VARUNSETALL}} commands available in SuperMacro. You can wait for the official release or get the latest version in the #beta channel on my discord server. http://discord.barraider.com
