### ISSUE TITLE
[Suggestion] Key press Timing

### ISSUE THREAD

**Issue by thowtue** [BarRaider/streamdeck-supermacro#3]
Hi, 
Will be nice to add the press time of a key, like if i hold for more than 100ms or 1000ms etc !

Also if you can extend the delay timing up to 10s or more if possible because i know that i will need more than 2s delay between key presses for my macros !

Thank you ! :)

**Comment by BarRaider** [comment]
Regarding the second suggestion: Try using the {{PAUSEXX}} command.
Where xxxx is a delay in milliseconds. So PAUSE9000 will pause for 9 seconds etc.

**Comment by thowtue** [comment]
Allright Thank you !
