### ISSUE TITLE
Numeric Keypad +, -, *, /

### ISSUE THREAD

**Issue by salasidis** [BarRaider/streamdeck-supermacro#30]
I could not find any {xxx} key map for the above keys on the number keypad.

Also a good feature would be to use a predefined key to signal key capture.

Ie if say key "Right Windows" is predefined as the key to capture keys (could be changed by the user in the main stream deck menu), then when that key is pressed, any other key pressed will auto generate its {XXX} equivalent code

**Comment by BarRaider** [comment]
All exist under the command section in the readme.md doc. Search for "oem"

**Comment by salasidis** [comment]
I don’t think {{CTRL}{OEM_PLUS}} is simulating a Ctrl / NUMpad+, it seems to be simulating the main keyboard plus.

It does not result in the action I expect in my software, whereas using a Hotkey Multiaction with the Ctrl/Numpad+ does.

Is it possible to verify this

Thanks

Robert
