### ISSUE TITLE
How to repeat ctrl-n ??

### ISSUE THREAD

**Issue by pmaillot** [BarRaider/streamdeck-supermacro#32]
Hello, more a call for help maybe than an issue :)
I have a macro: {{ctrl}{n}}{{pause:100}} and would like it to repeat as long as I keep the respective StreamDeck key pressed. UNfortunately this doesn't take place. The macro is generated/sent only when the key is released. What did I missed?
Thanks a lot,
-Patrick

**Comment by BarRaider** [comment]
You can try and use the SuperMacro PTT for that, with a 100ms delay. If you need support you can visit the Discord server: http://discord.barraider.com

**Comment by pmaillot** [comment]
EDIT: Actually what I need to enter is single ctrl-n or ctrl-p, or other single control characters, repeated every n milliseconds. This works well with SuperMacro with {{ctrl}{n}}{{pause:100}}, except repeat doesn't work.
Keystroke PTT does repeat for characters such as {{a}} or other printable characters, but not for single ctrl characters. So the sequence {{ctrl}{n}} does not work, Windows doesn't echo the character as it does when using SuperMacro; 

I guess there needs to be some kind of delay (as there is for SuperMacro) in KeystrokePTT, and on top of that having a repeat speed option would be great.

**Comment by pmaillot** [comment]
>>>SuperMacro PTT for that, with a 100ms delay

I've tried all sorts of {pause:100}, {{pause:100}} and without ':' and there's no delay showing in the repeat, so this doesn't seem to work.
