### ISSUE TITLE
StreamPortal Actions

### ISSUE THREAD

**Issue by eplab1745** [BarRaider/streamdeck-supermacro#33]
Is there direct functionality for supermacro to activate another button or profile without grouping it into a multi-action? One use for this would clicking a macro button in a nested folder and then immediately bouncing back to the parent level. Great software BTW, has allowed me to transition from autohotkey which is no easy task.

**Comment by BarRaider** [comment]
The current StreamDeck SDK does not allow a plugin to interact with any other plugin. That said, if you use profiles instead of folders (which is overall the best practice) you can use SuperMacro + Switch To Profile action bundled into one Multi-action
