### ISSUE TITLE
Pause/Break key?

### ISSUE THREAD

**Issue by clemon79** [BarRaider/streamdeck-supermacro#4]
Since {PAUSE} seems to be being used for actual pausing functionality, is there a command to use for the actual Pause/Break key? I need to be able to do {{lctrl}{lalt}{break}} or some such.

**Comment by BarRaider** [comment]
Sorry for the delay here. The command you're looking for is {{SNAPSHOT}} .

**Comment by clemon79** [comment]
Actually it looks like it's {BREAK} for Pause/Break, which is exactly what it should be. :) Question now is how do I get this upgraded to 1.1 in StreamDeck?

**Comment by BarRaider** [comment]
Yes, it is BREAK.
Sorry I misread.
 A new version of the plugin will be officially released in a few days. You can test it out prior on my discord server (link at https://barraider.github.io )

**Comment by clemon79** [comment]
Got it! Registered for and installed the beta from Discord, but {{BREAK}} doesn't seem to be working. Couple things here: I notice that it appears to behave differently if it's CTRL'd (the KVM software I am using this with differentiates between ControlBreak and Pause (while still acknowledging LControl), but I notice that if I set it to just Pause (with no shifters) that {{BREAK}} by itself wasn't working with that software either. So it may be that I just have to set a different hotkey to do that that behaves a little more standard-ish.
