### ISSUE TITLE
Keystrokes executed out of order

### ISSUE THREAD

**Issue by EricTeague** [BarRaider/streamdeck-supermacro#42]
I am playing a game (Fallout76) and trying to setup a macro with a delay.

Here is the original:

`
{{KeyDown:i}}

{{KeyUp:i}}
{{Pause:250}}
{{KeyDown:t}}
{{KeyUp:t}}
{{Pause:1500}}
{{KeyDown:1}}
{{KeyUp:1}}
{{Pause:1000}}
{{Pause:1000}}
{{KeyDown:tab}}
{{KeyUp:tab}}
`

The "i" and "t" are recognized and execute normally but the  "1" (after the 1500 pause) is not recognized but the closing "tab" is.

So I created another macro to isolate the issue:

`
{{KeyDown:1}}

{{KeyUp:1}}
{{Pause:1000}}
{{KeyDown:tab}}
{{KeyUp:tab}}`

I manually enter an "i" and a "t" to open the interface.  When I run the macro, the "tab" immediately runs, then the pause, then the "1" (seems backward).

I created a macro using the Stream Deck's System - HotKey to see if that interface would not accept commands from the Stream Deck and it recognized both the "1" and the "Tab".

I have to use "KeyUp/Down" as it is not recognizing the use of {{i}}, {{t}}, etc.

**Comment by BarRaider** [comment]
Hi, support is available through Discord. http://discord.barraider.com

Regardless, the best practice is to put a pause BETWEEN a keydown and a keyup, otherwise you can just do {{i}}
