### ISSUE TITLE
WIN button doesn't work properly

### ISSUE THREAD

**Issue by wenxiao2012** [BarRaider/streamdeck-supermacro#43]
I tried to use the key combination with WIN key, but it didn't work properly, and the correct key input couldn't be detected in the software and system.

`{{KeyDown:WIN}}
{{KeyDown:c}}
{{KeyUp:c}}
{{KeyUp:WIN}}`

**Comment by BarRaider** [comment]
Win-C is not a standard Windows shortcut, so not sure which App is supposed to be listening to this.
I have, however, tested both `{{win}{r}}` and `{{KeyDown:WIN}} {{KeyDown:r}} {{KeyUp:r}} {{KeyUp:WIN}}` and they both run the Windows Run command

**Comment by wenxiao2012** [comment]
Thank you for your reply.
Win+c is a shortcut key combination in simulated flight games.
Actually, I'm testing. Even under the windows desktop, trying to use the shortcut keys of win+d is still unsuccessful. It seems that the system has received more than one press and pop-up of win button.
When I tested {{keydown: win}} {{keydown: r}} {{keyup: r}} {{keyup: win}}, I could really open the run dialog, but two were opened at the same time, and multiple spaces were automatically entered in the latter dialog.
I use logitech's DIview to observe the input signal, and the press and pop-up of win button from the physical keyboard can be recorded normally. However, the win button action from supermacro cannot be captured. Similarly, I can't capture the win button action from supermacro in other tools for capturing buttons.
Meanwhile, other function keys such as shift and alt from supermacro and physical keyboard are normal.

**Comment by BarRaider** [comment]
In your example above you really have spaces between the different commands so it's very likely it will input spaces. Remember this is a keyboard simulator not a scripting language. It outputs whatever you have in the textbox, including spaces.
I recommend deleting the key, reinstalling the plugin, and starting from scratch. Those are not typical behaviors, and do not reproduce.
You can head over to our Discord if you would like support: http://discord.barraider.com
