### ISSUE TITLE
"Sticky" mode doesn't seem to work in some applications

### ISSUE THREAD

**Issue by risitt** [BarRaider/streamdeck-supermacro#5]
I was hoping to use this to create, as suggested by the Sticky Keystroke option, an autorun button for a particular game (Satisfactory) - by constantly sending the "w" character.

Unfortunately, while keystroke commands using the Stream Deck's built-in "HotKey" function work correctly (except that they aren't "sticky"), the Sticky Keystroke option in Supermacro is not detected by the game at all.

I've made sure the Stream Deck software is "elevated" (admin mode) as the lack of that can apparently cause macros to be unrecognized by some applications.

Your plugin does spam a bunch of w's into text editors, so I know that the Sticky Keystroke option is sending multiple keystrokes of the correct value. They just aren't being recognized by the game. Because the built-in macros work in the same game, there must be something different between the approach taken by your plugin and whatever Elgato is doing.

I did some reading on keyboard protocols, typematic delays and repeats, etc and suspect either a timing issue or the need to send key events rather than just repeated keypresses. I tried using the Sticky Super Macro mode with different delays of 1, 10, 30, 60, 100, and 1000 ms, so a simple timing issue seems unlikely.

The test at 1 ms might have revealed a clue: it prevented forward movement in game using the "w" key, but not backwards or sideways movement using "a", "s", or "d". Is the game interpreting all of the keypresses as "release" events? If your plugin is making the game think that the w key is being rapidly pressed and released, instead of just pressed and held, that may be the case.

In any case, Elgato seems to have either avoided or solved this problem, so I wonder if there is something exposed in their SDK that would do the trick?

**Comment by risitt** [comment]
Update: the game has a built-in chat. The keypresses are recognized in the chat, but not in the game itself. Seems to further support the idea that the game may not being seeing a "held" state, just a numerous rapid-fire press and release events.

**Comment by risitt** [comment]
Last update for now: there is a macro utility called AutoHotKey which can sort of get along with the Stream Deck in a bit of a roundabout way to emulate a held key. I used it to send separate down and up events for the "w" key, which worked flawlessly for an auto run button, but does not result in numerous "w" characters being spammed into a text editor. So, solve one problem, create another! It looks like faking a physical keyboard with software is no trivial task, let's hope the Stream Deck SDK has the tool you need!

Because I've "solved" my issue, a fix is not a high priority from my point of view, but it may well be something other people are looking for. In the meantime I may experiment with the SDK, and if I find a solution, I can let you know.

**Comment by eleven29** [comment]
I have the same problem in Star Citizen where, like @risitt, I tried to set up an auto run button ("w"). I'm pretty confident that he is on the right track suggesting the game might ignore spamming the 'walk' key. I set my keyboard to auto-repeat (8x) to test it and pressing the walk key then results in the character not being able to walk normally anymore. I'm hoping the SDK allows this to be addressed at all...

**Comment by BarRaider** [comment]
Sorry for the delay here. A new version of the plugin will be released in a few days which has two additional modes which could possibly solve your issue. You can test it out prior on my discord server (link at https://barraider.github.io )
Also, keep in mind some games would expect something like {{shift}{w}} to trigger the "W" key.

**Comment by risitt** [comment]
Hi BarRaider,

Not fixed...

I gave the newest version a try and still couldn't get it to work, using the "delayed keydown mode". As before, the sticky/PTT modes are acting as auto-clickers (rapidly repeating the macros), which is quite a bit different than the hoped-for effect. Holding down a key should only fire a single keyup event at the very end.

I used this website to visualize the problem with your plugin: https://javascript.info/keyboard-events

Here is what holding down a key on my keyboard does:

```
keydown key=w code=KeyW
--------------------------------------------------------------------------------
keydown key=w code=KeyW (repeat)
keydown key=w code=KeyW (repeat)
keydown key=w code=KeyW (repeat)
keydown key=w code=KeyW (repeat)
keyup key=w code=KeyW
```

So, you can see only a single keyup event, and multiple keydown events, only the first of which is identified as a new event, while the subsequent four are identified as repeats.

Here is what happens if I use your Sticky Keystroke action to attempt the same:

```
keydown key=w code=
keyup key= code=
keydown key=w code=
keyup key= code=
keydown key=w code=
keyup key= code=
keydown key=w code=
keyup key= code=
keydown key=w code=
keyup key= code=
```

So it's not holding down the key, it's just pressing it rapidly. Unfortunately, as long as the plugin continues to work in this way, it will remain incompatible with many applications.

**Comment by BarRaider** [comment]
Thanks for the deep dive here @risitt , this is extremely helpful and having a website to test it on is great.
Reopening this and will try to address it again

**Comment by risitt** [comment]
Awesome, thanks! I think there are relatively few of us trying to use the Streamdeck for gaming, and I'm really glad you're working to give us some better tools :)

Some people really do want an "auto-clicker", of course. A checkbox that enables "Hold button" modes for the Sticky Super Macro, Stick Keystroke, and Keystroke PTT actions would probably cover all the bases. The existing repeat-based method is still useful for some cases, I'm sure!

**Comment by BarRaider** [comment]
@risitt 
Checked again. Here is the output in your tool with the {{w}} sticky keystroke:

keydown key=w code=KeyW
keydown key=w code=KeyW (repeat)
keydown key=w code=KeyW (repeat)
keydown key=w code=KeyW (repeat)
keydown key=w code=KeyW (repeat)
keydown key=w code=KeyW (repeat)
keydown key=w code=KeyW (repeat)
keydown key=w code=KeyW (repeat)

It seems identical to yours... Maybe you were using "w" instead of {{w}} ?

**Comment by risitt** [comment]
Huh, I could have sworn I was using {{w}}, but you're right! And it's actually working. Flawlessly. 

FYI sticky keystroke doesn't quite act as expected with the mouse button, though, it repeatedly presses it instead of holding it down. But since that wasn't the original problem, I'd call this fixed!

Sorry for the confusion!
