### ISSUE TITLE
Backslash

### ISSUE THREAD

**Issue by alcmann** [BarRaider/streamdeck-supermacro#6]
Greetings, on latest pull, Do not see support for Backslash   {\}  Can this be added easily or possibly I can add the command for the macro manually ? 

Thanks

**Comment by BarRaider** [comment]
Next version should support automatically escaping the curly braces. I will be publishing a beta version today or tomorrow that you can test out. Will be published on my Discord server.
Link is at https://barraider.github.io

**Comment by alcmann** [comment]
Excellent Thanks @BarRaider
